apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchservice
spec:
  replicas: 3  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: searchservice
  template:
    metadata:
      labels:
        app: searchservice
    spec:
      containers:
        - name: searchservice
          image: "$(DOCKER_USERNAME)/searchservice:latest"  # Dùng biến từ ConfigMap
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dockerhub-config
                  key: DOCKER_USERNAME
          ports:
            - containerPort: 9005
---
apiVersion: v1
kind: Service
metadata:
  name: searchservice
spec:
  ports:
    - port: 9005
      targetPort: 9005
  selector:
    app: searchservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
