CREATE TABLE IF NOT EXISTS PROVINCES(
    code INT NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    codeName VARCHAR(75) NOT NULL,
    divisionType VARCHAR(100) NOT NULL,
    isActive BOOLEAN DEFAULT true
);