CREATE TABLE IF NOT EXISTS ADDRESSES(
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    province_id INT NOT NULL,
    district_id INT NOT NULL,
    ward_id INT,
    phone VARCHAR(14),
    isActive BOOLEAN DEFAULT true,
    houseNumberAndStreet VARCHAR(150) DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (province_id) REFERENCES PROVINCES(code) ON DELETE CASCADE,
    FOREIGN KEY (district_id) REFERENCES DISTRICTS(code) ON DELETE CASCADE,
    FOREIGN KEY (ward_id) REFERENCES WARDS(code) ON DELETE SET NULL
    )