CREATE TABLE IF NOT EXISTS USER_ADDRESSES (
    user_id VARCHAR(255) NOT NULL,
    address_id VARCHAR(255) NOT NULL,
    isDefault BOOLEAN DEFAULT false,
    PRIMARY KEY (user_id, address_id),
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (address_id) REFERENCES ADDRESSES(id) ON DELETE CASCADE
    );