apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
spec:
  replicas: 2  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: ${{secrets.DOCKER_USERNAME}}/notificationservice:latest
          ports:
            - containerPort: 9004
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
spec:
  ports:
    - port: 9004
      targetPort: 9004
  selector:
    app: notificationservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
