services:
  discoveryserver:
    build:
      context: .
      dockerfile: discoveryserver/Dockerfile
    image: ntt23042003/discoveryserver:latest
    ports:
      - "8761:8761"

  userservice:
    build:
      context: .
      dockerfile: userservice/Dockerfile
    image: ntt23042003/userservice:latest
    ports:
      - "9000:9000"

  mediaservice:
    build:
      context: .
      dockerfile: mediaservice/Dockerfile
    image: ntt23042003/mediaservice:latest
    ports:
      - "9001:9001"

  productservice:
    build:
      context: .
      dockerfile: productservice/Dockerfile
    image: ntt23042003/productservice:latest
    ports:
      - "9002:9002"
  orderservice:
    build:
      context: .
      dockerfile: orderservice/Dockerfile
    image: ntt23042003/orderservice:latest
    ports:
      - "9003:9003"
  notificationservice:
    build:
      context: .
      dockerfile: notificationservice/Dockerfile
    image: ntt23042003/notificationservice:latest
    ports:
      - "9004:9004"

  searchservice:
    build:
      context: .
      dockerfile: searchservice/Dockerfile
    image: ntt23042003/searchservice:latest
    ports:
      - "9005:9005"
  chatservice:
    build:
      context: .
      dockerfile: chatservice/Dockerfile
    image: ntt23042003/chatservice:latest
    ports:
      - "9006:9006"
  authservice:
    build:
      context: .
      dockerfile: authservice/Dockerfile
    image: ntt23042003/authservice:latest
    ports:
      - "9009:9009"

  apigateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    image: ntt23042003/apigateway:latest
    ports:
      - "8080:8080"
