apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
spec:
  replicas: 1  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - name: chatservice
          image: ntt23042003/chatservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9006
---
apiVersion: v1
kind: Service
metadata:
  name: chatservice
spec:
  ports:
    - port: 9006
      targetPort: 9006
  selector:
    app: chatservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatservice
  minReplicas: 1
  maxReplicas: 2  # Tự động scale tối đa 3 replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Scale khi CPU sử dụng vượt quá 75%
