apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - name: chatservice
          image: chatservice:local
          imagePullPolicy: Never
          ports:
            - containerPort: 9006
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9006
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9006
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: chatservice
spec:
  type: NodePort  # ✅ Expose ra ngoài cho Eureka & API Gateway
  selector:
    app: chatservice
  ports:
    - port: 9006
      targetPort: 9006
      nodePort: 30906  # ✅ Truy cập từ bên ngoài qua http://hdan-3:30906
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatservice
  minReplicas: 1
  maxReplicas: 3  # ✅ Sửa lại đúng mô tả
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
