server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://hdan-2:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: hdan-3
    non-secure-port: 30902
    instance-id: productservice:${random.uuid}

spring:
  datasource:
    url: jdbc:mysql://hdan-1:30307/productservicedb
    username: productservice
    password: productservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    enable: true
    bootstrap-servers: hdan-1:30992
    consumer:
      group-id: product-group

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    uris: http://hdan-1:30920  # Elasticsearch NodePort từ Cloud 1

  data:
    web:
      pageable:
        default-page-size: 15
    redis:
      port: 30379             # Redis exposed tại Cloud 1
      host: hdan-1

  config:
    import: classpath:application-common.yml

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.batch.internal: OFF
    org.hibernate.engine.transaction.internal: OFF
    org.springframework: INFO
