server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://10.32.2.32:30861/eureka
  instance:
    prefer-ip-address: true
    ip-address: 10.32.2.54
    non-secure-port: 30902
    instance-id: productservice:${random.uuid}

spring:
  datasource:
    url: jdbc:mysql://10.32.2.21:30307/productservicedb
    username: productservice
    password: productservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    enable: true
    bootstrap-servers: 10.32.2.21:30992
    consumer:
      group-id: "default-group"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    uris: http://10.32.2.21:30920  # Elasticsearch NodePort từ Cloud 1

  data:
    web:
      pageable:
        default-page-size: 15
    redis:
      port: 30379             # Redis exposed tại Cloud 1
      host: 10.32.2.21

  config:
    import: classpath:application-common.yml

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.batch.internal: OFF
    org.hibernate.engine.transaction.internal: OFF
    org.springframework: INFO
