server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Dataconfig
spring:
  config:
    import: optional:file:../commonservice/src/main/resources/application.yml
  datasource:
    url: jdbc:mysql://localhost:3307/productservicedb
    username: productservice
    password: productservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: http://localhost:9200
  data:
    web:
      pageable:
        default-page-size: 15
logging:
  level:
    org.hibernate.SQL: OFF                       # Tắt log câu truy vấn SQL
    org.hibernate.type.descriptor.sql: OFF       # Tắt log thông tin ràng buộc tham số
    org.hibernate.engine.jdbc.batch.internal: OFF # Tắt log về batch SQL
    org.hibernate.engine.transaction.internal: OFF # Tắt log về transaction
    org.springframework: ERROR                    # Kiểm soát log của Spring
