apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
spec:
  replicas: 1  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: ntt23042003/notificationservice:latest  # Dùng biến từ ConfigMap
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9004

---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
spec:
  ports:
    - port: 9004
      targetPort: 9004
  selector:
    app: notificationservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notificationservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationservice
  minReplicas: 1
  maxReplicas: 2  # Tự động scale tối đa 5 replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Scale khi CPU sử dụng vượt quá 75%
