server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 #trong 1s nap lai 10 token
                redis-rate-limiter.burstCapacity: 20 #toi da 20 packega token
                redis-rate-limiter.requestedTokens: 1 # so luong request tieu thu n token
        - id: MediaService
          uri: lb://MediaService
          predicates:
            - Path=/api/v1/upload/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 #trong 1s nap lai 10 token
                redis-rate-limiter.burstCapacity: 20 #toi da 20 packega token
                redis-rate-limiter.requestedTokens: 1 # so luong request tieu thu n token
eureka:
  instance:
    hostname: discoveryserver
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  data:
    redis:
      port: 6379
      host: localhost