apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-server:7.7.0
          ports:
            - containerPort: 9092  # Cổng Kafka
            - containerPort: 9101  # Cổng JMX metrics
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker:9092"
            - name: KAFKA_LISTENER_NAME_PLAINTEXT
              value: "PLAINTEXT"
            - name: KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID
              value: "anonymous"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
          livenessProbe:
            exec:
              command:
                - nc
                - -zv
                - localhost
                - "9092"
            initialDelaySeconds: 60  # Đặt thời gian delay lớn hơn để Kafka có thời gian khởi động
            periodSeconds: 30        # Giảm tần suất kiểm tra
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - nc
                - -zv
                - localhost
                - "9092"
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
