apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-connector-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-connector-java-8.0.30.jar"  # Đường dẫn trên Minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-connector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
