apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort  # ✅ Thêm dòng này để expose Redis ra ngoài
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379  # ✅ Redis sẽ truy cập qua <cloud3-ip>:30379
