apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoveryserver
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        - name: discoveryserver
          image: "discoveryserver:latest"  # Dùng biến từ ConfigMap
          env:
             - name: DOCKER_USERNAME
               value: ntt23042003
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: discoveryserver
  type: ClusterIP
