apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaservice
spec:
  replicas: 2  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: mediaservice
  template:
    metadata:
      labels:
        app: mediaservice
    spec:
      containers:
        - name: mediaservice
          image: "$(DOCKER_USERNAME)/mediaservice:latest"  # Dùng biến từ ConfigMap
          env:
            - name: DOCKER_USERNAME
              value: ntt23042003
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker:9092"
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: mediaservice
spec:
  ports:
    - port: 9001
      targetPort: 9001
  selector:
    app: mediaservice
  type: ClusterIP # Đảm bảo service có thể được truy cập nội bộ
