apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 3  # ✅ Bắt đầu với 3 pod thay vì 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: productservice:local
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "hdan-1:30992"
            - name: KAFKA_GROUP_ID
              value: "product-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9002
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9002
            initialDelaySeconds: 15
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  type: NodePort
  selector:
    app: productservice
  ports:
    - port: 9002
      targetPort: 9002
      nodePort: 30902

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productservice
  minReplicas: 3  # ✅ Tối thiểu vẫn giữ 3 pod chạy
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
