apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 3  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: "$(DOCKER_USERNAME)/productservice:latest"  # Dùng biến từ ConfigMap
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dockerhub-config
                  key: DOCKER_USERNAME
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker:9092"
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: productservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
