apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 1  # Tăng số lượng replicas lên 3
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: ntt23042003/productservice:latest  # Dùng biến từ ConfigMap
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: productservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productservice
  minReplicas: 1
  maxReplicas: 2  # Tự động scale tối đa 8 replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Scale khi CPU sử dụng vượt quá 75%
