server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka

axon:
  eventhandling:
    processors:
      default:
        mode: tracking
        token-store:
          type: jdbc   # Lưu trạng thái vào database
        retry-max-attempts: 3
        retry-exponential-backoff:
          initial-interval: 1000  # Lần đầu retry sau 1s
          max-interval: 60000     # Giới hạn tối đa 60s
          multiplier: 2.0         # Tăng dần thời gian retry (1s, 2s, 4s, ...)
#        error-handler: logging  # Chỉ log lỗi, không retry


#Dataconfig
spring:
  datasource:
    url: jdbc:mysql://userservicedb:3306/userservicedb
    username: userservice
    password: userservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: user-group
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - optional:file:../commonservice/src/main/resources/application.yml

logging:
  level:
    org.hibernate.SQL: off                     # Tắt log câu truy vấn SQL
    org.hibernate.type.descriptor.sql: OFF       # Tắt log thông tin ràng buộc tham số
    org.hibernate.engine.jdbc.batch.internal: OFF # Tắt log về batch SQL
    org.hibernate.engine.transaction.internal: OFF # Tắt log về transaction
    org.springframework: INFO               # Kiểm soát log của Spring
    org.axonframework.eventhandling: DEBUG
    org.axonframework.commandhandling: DEBUG

