server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Dataconfig
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb
    username: userservice
    password: userservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    default-schema: userservicedb
    baseline-on-migrate: true  # Tạo baseline nếu chưa có schema

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


