server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://10.32.2.32:30861/eureka
  instance:
    prefer-ip-address: true
    ip-address: 10.32.2.54
    non-secure-port: 30900
    instance-id: userservice:${random.uuid}

axon:
  eventhandling:
    processors:
      default:
        mode: tracking
        token-store:
          type: jdbc
        retry-max-attempts: 3
        retry-exponential-backoff:
          initial-interval: 1000
          max-interval: 60000
          multiplier: 2.0
#        error-handler: logging

spring:
  config:
    import: classpath:application-common.yml

  datasource:
    url: jdbc:mysql://10.32.2.21:30306/userservicedb
    username: userservice
    password: userservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    enable: true
    bootstrap-servers: 10.32.2.21:30992
    consumer:
      group-id: user-group

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.batch.internal: OFF
    org.hibernate.engine.transaction.internal: OFF
    org.springframework: INFO
    org.axonframework.eventhandling: DEBUG
    org.axonframework.commandhandling: DEBUG
