server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



#Dataconfig
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb
    username: userservice
    password: userservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: OFF                       # Tắt log câu truy vấn SQL
    org.hibernate.type.descriptor.sql: OFF       # Tắt log thông tin ràng buộc tham số
    org.hibernate.engine.jdbc.batch.internal: OFF # Tắt log về batch SQL
    org.hibernate.engine.transaction.internal: OFF # Tắt log về transaction
    org.springframework: ERROR                    # Kiểm soát log của Spring

