server:
  port: 9009


eureka:
  client:
    service-url:
      defaultZone: http://hdan-2:8761/eureka

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://authservice:9009/api/v1/auth
      resourceserver:
        jwt:
          issuer-uri: http://authservice:9009/api/v1/auth
  kafka:
    enabled: false
  config:
    import: classpath:application-common.yml

logging:
  level:
    org.springframework.security: TRACE
