server:
  port: 9009


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    instance:
      prefer-ip-address: true
      ip-address: 10.32.2.54
      nonSecurePort: 30909
      instance-id: ${spring.cloud.client.ip-address}:${random.uuid}
    service-url:
      defaultZone: http://10.32.2.32:30861/eureka

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://authservice:9009/api/v1/auth
      resourceserver:
        jwt:
          issuer-uri: http://authservice:9009/api/v1/auth
  kafka:
    enabled: false
  config:
    import: classpath:application-common.yml

logging:
  level:
    org.springframework.security: TRACE
