server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanouscompany@gmail.com
    password: deuxfgnsgporftew
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # config:
  #   import: optional:file:../commonservice/src/main/resources/application.yml
  kafka:
    enabled: true
    bootstrap-servers: broker-kafka-bootstrap.kafka.svc.cluster.local:9092
  config:
    import: classpath:application-common.yml
    #consumer:
     # group-id: mail-group
logging:
  level:
    org.hibernate.SQL: OFF                       # Tắt log câu truy vấn SQL
    org.hibernate.type.descriptor.sql: OFF       # Tắt log thông tin ràng buộc tham số
    org.hibernate.engine.jdbc.batch.internal: OFF # Tắt log về batch SQL
    org.hibernate.engine.transaction.internal: OFF # Tắt log về transaction
    org.springframework: ERROR                    # Kiểm soát log của Spring