server:
  port: 9004

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://10.32.2.32:30861/eureka
  instance:
    prefer-ip-address: true
    ip-address: 10.32.2.54
    non-secure-port: 30904
    instance-id: notificationservice:${random.uuid}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanouscompany@gmail.com
    password: deuxfgnsgporftew
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    enabled: true
    bootstrap-servers: 10.32.2.21:30992
    consumer:
      group-id: mail-group

  config:
    import: classpath:application-common.yml

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.batch.internal: OFF
    org.hibernate.engine.transaction.internal: OFF
    org.springframework: ERROR
