spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:default-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
jwt:
  secret: "YMRaDBMR5ogwC2qr5zadtmz+1Tx1QRp3mg/LPlUjCxg="
  expiration: 3600000  # 1 giờ (Access Token)
  #expiration: 60000  # 1 phút (Access Token)
  refresh-expiration: 604800000  # 7 ngày (Refresh Token)
  issuer: http://localhost:8080/api/v1/auth
  permitted-urls:
    - "/**"
    - "/api/v1/auth/login"
    - "/api/v1/auth/logout"
    - "/api/v1/auth/refresh"
    - "/api/v1/products/**"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/swagger-resources/**"
    - "/webjars/**"

