apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: ntt23042003/orderservice:latest  # Dùng biến từ ConfigMap
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_USERNAME
              value: ntt23042003
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  ports:
    - port: 9003
      targetPort: 9003
  selector:
    app: orderservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orderservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orderservice
  minReplicas: 1
  maxReplicas: 2  # Tự động scale tối đa 3 replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Scale khi CPU sử dụng vượt quá 75%
