apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: ntt23042003/orderservice:latest
          imagePullPolicy: Never
          env:
            - name: DOCKER_USERNAME
              value: ntt23042003
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "hdan-1:30992"  # Kết nối Kafka ngoài cụm
            - name: KAFKA_GROUP_ID
              value: "order-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9003
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9003
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: NodePort  # ✅ Expose ra ngoài
  selector:
    app: orderservice
  ports:
    - port: 9003
      targetPort: 9003
      nodePort: 30903  # ✅ Truy cập từ Cloud 2 qua http://hdan-3:30903

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orderservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orderservice
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
