apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 2  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: "$(DOCKER_USERNAME)/orderservice:latest"  # Dùng biến từ ConfigMap
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dockerhub-config
                  key: DOCKER_USERNAME
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker:9092"
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  ports:
    - port: 9003
      targetPort: 9003
  selector:
    app: orderservice
  type: ClusterIP  # Đảm bảo service có thể được truy cập nội bộ
