app:
  base-url: ${APP_BASE_URL:http://localhost:80}

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Dataconfig
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/orderservicedb
    username: orderservice
    password: orderservice2425
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
  config:
    import: file:../commonservice/src/main/resources/application.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 15
logging:
  level:
    org.hibernate.SQL: OFF                       # Tắt log câu truy vấn SQL
    org.hibernate.type.descriptor.sql: OFF       # Tắt log thông tin ràng buộc tham số
    org.hibernate.engine.jdbc.batch.internal: OFF # Tắt log về batch SQL
    org.hibernate.engine.transaction.internal: OFF # Tắt log về transaction
    org.springframework: ERROR                    # Kiểm soát log của Spring

payment:
  vnpay:
    hashSecret: MQN1ZKF963OHI8TZ9MJUB7IGJE9OSZP5
    tmnCode: 03ECV6B1
    returnUrl: http://localhost:8080/api/v1/orders/vnpay/callback
    create:
      endpoint: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    query:
      endpoint: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction?vnp_Command=querydr
    refund:
      endpoint: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction?vnp_Command=refund
    version: 2.1.0
    orderType: other
  zalopay:
    appid: 554
    key1: 8NdU5pG5R2spGHGhyO99HN1OhD8IQJBn
    key2: uUfsWgfLkRLzq6W2uNXTCxrfxs51auny
    callback: http://localhost:8080/api/v1/orders/zalopay/callback
    returnUrl: http://localhost:3000/payment-result?status=%s&orderId=%s
    create:
      endpoint: https://sandbox.zalopay.com.vn/v001/tpe/createorder
    query:
      endpoint: https://sandbox.zalopay.com.vn/v001/tpe/getstatusbyapptransid
    refund:
      endpoint: https://sandbox.zalopay.com.vn/v001/tpe/partialrefund
ghtk:
  production:
    api:
      url:
        create: https://services.giaohangtietkiem.vn/services/shipment/order
        cancel: https://services.giaohangtietkiem.vn/services/shipment/cancel
        status: https://services.giaohangtietkiem.vn/services/shipment/v2
        label: https://services.giaohangtietkiem.vn/services/label
        fee: https://services.giaohangtietkiem.vn/services/shipment/fee
      token: 186BjTm18OSmkbCzz0HJVYV3j0UUtafYk2taARP
      secret: S22869201
  staging:
    api:
      url:
        create: https://services-staging.ghtklab.com/services/shipment/order
        cancel: https://services-staging.ghtklab.com/services/shipment/cancel
        status: https://services-staging.ghtklab.com/services/shipment/v2
        label: https://services-staging.ghtklab.com/services/label
        fee: https://services-staging.ghtklab.com/services/shipment/fee
      token: 73Cs59xTqgURo7LhVP2zSxAfDpSScrRkwXdp1U
      secret: S22869201