server:
  port: 9005

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://10.32.2.32:30861/eureka
  instance:
    prefer-ip-address: true
    ip-address: 10.32.2.54
    non-secure-port: 30905
    instance-id: searchservice:${random.uuid}

spring:
  config:
    import: classpath:application-common.yml

  kafka:
    enable: true
    bootstrap-servers: 10.32.2.21:30992  # ✅ NodePort Kafka tại Cloud 1

  elasticsearch:
    uris: http://10.32.2.21:30920  # ✅ NodePort Elasticsearch tại Cloud 1

  data:
    web:
      pageable:
        default-page-size: 15
    redis:
      host: 10.32.2.21           # ✅ Redis Host (Cloud 1)
      port: 30379            # ✅ Redis NodePort (Cloud 1)

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.batch.internal: OFF
    org.hibernate.engine.transaction.internal: OFF
    org.springframework: INFO
