server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://hdan-1:8761/eureka

#Dataconfig
spring:
  # config:
  #   import: optional:file:../commonservice/src/main/resources/application.yml
  config:
    import: classpath:application-common.yml
  kafka:
    enable: true
    bootstrap-servers: 30379
  elasticsearch:
    uris: hdan-1:30920
  data:
    web:
      pageable:
        default-page-size: 15
    redis:
      port: 30379
      host: hdan-1
logging:
  level:
    org.hibernate.SQL: OFF # Tắt log câu truy vấn SQL
    org.hibernate.type.descriptor.sql: OFF # Tắt log thông tin ràng buộc tham số
    org.hibernate.engine.jdbc.batch.internal: OFF # Tắt log về batch SQL
    org.hibernate.engine.transaction.internal: OFF # Tắt log về transaction
    org.springframework: INFO # Kiểm soát log của Spring
