apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 3  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: "$(DOCKER_USERNAME)/userservice:latest"  # Dùng biến từ ConfigMap
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dockerhub-config
                  key: DOCKER_USERNAME
          ports:
            - containerPort: 9005
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: userservice
  type: ClusterIP # Đảm bảo service có thể được truy cập nội bộ
