apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: userservice:local
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "hdan-1:30992"  # ✅ Sửa lại đúng địa chỉ kafka bên Cloud 1
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "500m"     # hoặc cao hơn nếu cần
              memory: "256Mi"
            limits:
              cpu: "2000m"    # = 2 core CPU (hoặc cao hơn tùy nhu cầu)
              memory: "512Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: NodePort  # ✅ Expose để gateway hoặc discovery bên ngoài có thể truy cập
  selector:
    app: userservice
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900  # ✅ Truy cập từ ngoài qua http://hdan-3:30900

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
