apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1  # Tăng số lượng replicas lên 2
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: ntt23042003/userservice:latest  # Dùng biến từ ConfigMap
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "broker-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9000
--- 
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: userservice
  type: ClusterIP # Đảm bảo service có thể được truy cập nội bộ
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
  minReplicas: 1
  maxReplicas: 2  # Tự động scale tối đa 5 replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # Scale khi CPU sử dụng vượt quá 75%
