apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: authservice:local
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "10.32.2.21:30750"  # Kafka NodePort ở Cloud 1
            - name: KAFKA_GROUP_ID
              value: "default-group"
            - name: BACKUP_ROOT_DIR
              value: "./app/data/backup-scripts/"
          ports:
            - containerPort: 9009
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9009
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9009
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: NodePort
  selector:
    app: authservice
  ports:
    - port: 9009
      targetPort: 9009
      nodePort: 30909  # Truy cập từ bên ngoài qua http://<cloud3-ip>:30909
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authservice
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
