  # This is a basic workflow that is manually triggered

name: CI/CD Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # push:
  #   branches:
  #     - deployment
  # pull_request:
  #   branches:
  #     - deployment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #pull repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    #install docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    #config login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
     #Build adn push Docker image for services
      - name: Build and push userservice Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/userservice:$GITHUB_SHA ./userservice
          docker push ${{secrets.DOCKER_USERNAME}}/userservice:$GITHUB_SHA
