server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://hdan-2:8761/eureka

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
  uploadAssetsName: ${CLOUDINARY_UPLOAD_ASSETS_NAME}


logging:
  level:
    org.springframework: INFO
spring:
  kafka:
    bootstrap-servers: hdan-1:30992
    consumer:
      group-id: upload-group
  config:
    import: classpath:application-common.yml
  # config:
  #   import: file:../commonservice/src/main/resources/application.yml