server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://hdan-2:8761/eureka  # Discovery Server ở Cloud 2
  instance:
    prefer-ip-address: true
    ip-address: hdan-3                         # 👈 Hostname của Cloud 3
    non-secure-port: 30901                     # 👈 NodePort của mediaservice
    instance-id: mediaservice:${random.uuid}

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
  uploadAssetsName: ${CLOUDINARY_UPLOAD_ASSETS_NAME}

logging:
  level:
    org.springframework: INFO

spring:
  kafka:
    bootstrap-servers: hdan-1:30992  # Kafka exposed qua NodePort ở Cloud 1
    consumer:
      group-id: upload-group
  config:
    import: classpath:application-common.yml
